### ISSUE TITLE
question about call addresses

### ISSUE THREAD

**Issue by pokamolodoy406** [mxmssh/drltrace#12]
how to print the function call address ?

I modified your code a little to print the addresses.

![2](https://user-images.githubusercontent.com/37054694/46448296-cfc6dd00-c78e-11e8-9851-85ffb8e0ea81.png)

for example: 
![2](https://user-images.githubusercontent.com/37054694/46448310-e1a88000-c78e-11e8-89c8-fc6d4f90b609.png)

the address is 0x0000000140001018    (he was interested in me) 

but in logfile  i see:

![default](https://user-images.githubusercontent.com/37054694/46448372-2c29fc80-c78f-11e8-8624-5d515fdb5e03.png)

how do I modify the code to print the correct addresses

**Comment by mxmssh** [comment]
Hi, the problem is that drltrace's function (where you modified dr_fprintf) is actually trigerred when program is already in system library (the adress 0x000007ff... belongs to system dll). So, to be able to print actual address you need to take the returning address from the stack. But I already implemented that, just specify ```-print_ret_addr``` option to drltrace. It will print offset + module unique ID. You can find a table with module IDs at the end of logfile.

**Comment by pokamolodoy406** [comment]
Thanks! ))
